# Generated by Django 6.0.2 on 2026-02-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMst',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Country_mst',
            },
        ),
        migrations.CreateModel(
            name='ProductMst',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'Product_mst',
            },
        ),
        migrations.CreateModel(
            name='SalesMaster',
            fields=[
                ('sales_master_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SalesMaster',
            },
        ),
        migrations.CreateModel(
            name='UsersMst',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'Users_mst',
            },
        ),
        migrations.CreateModel(
            name='CityMst',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.countrymst')),
            ],
            options={
                'db_table': 'City_mst',
            },
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('sales_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_sold', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.citymst')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.countrymst')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.productmst')),
                ('sales_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.salesmaster')),
            ],
            options={
                'db_table': 'SalesDetails',
            },
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.usersmst'),
        ),
    ]
